# Generated by Django 5.2.4 on 2025-08-18 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='use_email_as_user_ID',
        ),
    ]
