# Generated by Django 5.2.4 on 2025-08-17 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='bio',
            field=models.TextField(blank=True, help_text='Short biography of the instructor.', null=True),
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the certification.', max_length=255)),
                ('issuer', models.CharField(blank=True, help_text='Issuer of the certification.', max_length=255, null=True)),
                ('date_awarded', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, help_text='Expiration date of the certification.', null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='users.instructor')),
            ],
        ),
    ]
