# Generated by Django 5.2.5 on 2025-09-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_use_email_as_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='country',
            field=models.CharField(blank=True, help_text='Country of the instructor.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='location',
            field=models.CharField(blank=True, help_text='Location of the instructor.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='country',
            field=models.CharField(blank=True, help_text='Country of the instructor.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='location',
            field=models.CharField(blank=True, help_text='Location of the instructor.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='country',
            field=models.CharField(blank=True, help_text='Country of the instructor.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='location',
            field=models.CharField(blank=True, help_text='Location of the instructor.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
