# Generated by Django 5.2.4 on 2025-08-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_instructor_bio_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
